
export const RAW_CSV_DATA = `Client ID,Client Name,Full Name,Job Title,Manager
103098,Advanced Ground Systems Engineering LLC,"Aguilar, Alejandro ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Aguilar, Daniel ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Aguilar, Gildardo A.",Lead Fitter/Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Ahmad, Nazar ",Senior Planner,"Neer, Hans"
103098,Advanced Ground Systems Engineering LLC,"Amaya, Francisco ",QC Inspector - Receiving,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Andreani, David ",Maintenance,"Gutierrez, Jose Antonio"
103098,Advanced Ground Systems Engineering LLC,"Aranda, Gustavo V.",Operations Liaison,"Savalia, Lalit Babu"
103098,Advanced Ground Systems Engineering LLC,"Arenas, Matthew ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Arostegui, Antonio ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Arredondo, Phillip ",Lead Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Arrowchis, Bishop ",Manufacturing Engineer,"Neer, Hans"
103098,Advanced Ground Systems Engineering LLC,"Avalos Roa, Karla M.",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Baeza Gonzalez, Jorge L.",WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Balam, Rene ",Fitter-Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Banayos, Marian Michaelle F.",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Barajas Medina, Silvino ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Bonilla, Kelly ",Stencil Room Attendant,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Botello, Adolfo ",Machinist/ Programmer,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Boucher, Alberto ",MAINTENANCE TECH.,"Gutierrez, Jose Antonio"
103098,Advanced Ground Systems Engineering LLC,"Bustamante, Juan M.",PAINTER,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Canchola, Anthony ",Planner,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Caniz, Anibal ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Cepeda, Miguel A.",Quality Engineer,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Cetino, Axel ",Fitter-Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Chavez, Isabelle ",AP/ AR Generalist,"Tran, Tiffany"
103098,Advanced Ground Systems Engineering LLC,"Chikane, Omkar B.",Manufacturing Engineer,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Chupinij, Andrue ",FITTER/WELDER,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Cobos, Violeta ",HR Generalist,"Trejo-Maheshwari, Kam Kristy"
103098,Advanced Ground Systems Engineering LLC,"Contreras, Matthew A.",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Contreras, Ricardo ",Production Coordinator,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Cortez, Sergio ",Buyer,"Case, Nancy"
103098,Advanced Ground Systems Engineering LLC,"Covarrubias, Francisco ",Shipping Coordinator,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Cruz, Victor ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Curtade, Gloria E.",Q.A. Administrative Assistant,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Daniels, Quinten M.",Quality Control Inspector,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"De La Garza, Richard ",QC Inspector - Receiving,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Deveraux, Dylan ",Fitter-Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Diarte, Ryan ",Mechanical Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Eb, Heber ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Estrada, Fabiola A.",Associate Product Development Engineer,"Garcia-Barron, Ohtli Aciz"
103098,Advanced Ground Systems Engineering LLC,"Finnie, Devlin C.",Production Planning Engineer,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Flores, Victor M.",Fitter-Welder,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Franco, Francisco ",Hydraulic Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Garcia, Fernando ",Material Coordinator,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Garcia, Joel ",Production Coordinator Lead,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Garcia, Luis ",Production Planning Engineer,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Gleason, Jason E.",QC Inspector,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Gomez, Jose D.",Assembly Operations Lead,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Gomez, Lina ",Accounting Generalist,"Tran, Tiffany"
103098,Advanced Ground Systems Engineering LLC,"Gonzalez, Connie ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Gonzalez, Federico P.",WELDER,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Gonzalez, Fermin ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Gonzalez, Peter ",QC Inspector - Assembly,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Guerrero, Jun ",CAD Designer III,"Case, Stevan B"
103098,Advanced Ground Systems Engineering LLC,"Guerrero, Veronica A.",Accounting Generalist,"Tran, Tiffany"
103098,Advanced Ground Systems Engineering LLC,"Gutierrez, Juan A.",Fitter-Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Guzman, Luis A.",Material Prep,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Hernandez, David ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Jaime, Miguel ",Machinist Helper,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Jimenez, Jose M.",Combination Welder,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Jimenez, Nicholas ",Mechanical Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Juarez, Carlos ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Karis, Keith ",Senior Project Engineer,"Case, Stevan B"
103098,Advanced Ground Systems Engineering LLC,"Kim, Hoiwon ",Senior Business Analyst,"von Flottwell, Joerg Michael"
103098,Advanced Ground Systems Engineering LLC,"Lazo, Alexis ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Lepe, Priscilla ",Senior HR Generalist,"Trejo-Maheshwari, Kam Kristy"
103098,Advanced Ground Systems Engineering LLC,"Lin, Kevin ",Product Development Engineer,"Garcia-Barron, Ohtli Aciz"
103098,Advanced Ground Systems Engineering LLC,"Liu, Kevin ",Technical Writer/Illustrator,"Cuevas, Gerald"
103098,Advanced Ground Systems Engineering LLC,"Lopez, Bryant ",Mechanical Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Lopez, Edverth A.",QC Lead Inspector - Receiving,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Lopez, Yoni ",Material Handler/Proof Load,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Luquin, Harly ",Document Control Specialist,"Cuevas, Gerald"
103098,Advanced Ground Systems Engineering LLC,"Macias, Manuel ",Research & Development/ Project Engineer,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Magdaleno Avila, J Socorro ",Mechanical Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Maldonado, Christeam ",Sub-Assembly Lead Operator,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Martinez Miranda, Juan ",Machinist/ Programmer,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Martinez, Cruz ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Martinez, Juan ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Mejia, Miguel ",Mechanical Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Mercado Dominguez, Rafael ",Buyer,"Case, Nancy"
103098,Advanced Ground Systems Engineering LLC,"Monreal, Mario ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Montano Arevalo, Jose de Jesus ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Montes Reyes, Juan M.",WELDER,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Morales, John M.",MAINTENANCE TECH.,"Gutierrez, Jose Antonio"
103098,Advanced Ground Systems Engineering LLC,"Morales, Noe ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Munoz, Miguel ",Hydraulic Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Muro, Paul ",Product Development Engineer,"Garcia-Barron, Ohtli Aciz"
103098,Advanced Ground Systems Engineering LLC,"Nagraj, Rishikesh Madan ",Continuous Improvement Engineer,"Nair, Varun"
103098,Advanced Ground Systems Engineering LLC,"Nava, Connie ",Receptionist/ Administrative Assistant,"Trejo-Maheshwari, Kam Kristy"
103098,Advanced Ground Systems Engineering LLC,"Ngo, Hien T.",Senior Accountant,"Le, Minh Tran"
103098,Advanced Ground Systems Engineering LLC,"Nguyen, Jonathan H.",Production Planning Engineer,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"OO, Wai Zin ",Product Development Engineer,"Garcia-Barron, Ohtli Aciz"
103098,Advanced Ground Systems Engineering LLC,"Ormeno, Walter ",Maintenance,"Gutierrez, Jose Antonio"
103098,Advanced Ground Systems Engineering LLC,"Pacheco, J F.",Production Coordinator,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Pang, Yoeurth ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Pasmant, Nicholas R.",Production Coordinator,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Pealo, Jason P.",Engineering Systems Specialist,"Case, Stevan B"
103098,Advanced Ground Systems Engineering LLC,"Perez, Terry ",Maintenance,"Gutierrez, Jose Antonio"
103098,Advanced Ground Systems Engineering LLC,"Ramirez, Jessica ",Stencil Room Attendant,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Ramirez, Ramon ",Senior Help Desk Specialist,"Valles, Sergio"
103098,Advanced Ground Systems Engineering LLC,"Ramirez, Ricardo ",QC Lead Inspector - Assembly,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Randall, Thomas J.",Inventory Lead,"Ramos, Javier"
103098,Advanced Ground Systems Engineering LLC,"Reynaga, Jorge ",QC Inspector - Assembly,"Grayum, Daniel J"
103098,Advanced Ground Systems Engineering LLC,"Reynoso, Nicholas ",Material Handler Lead,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Rico, Manuel ",Mechanical Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Rocha, Dylan ",FITTER/WELDER,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Armando ",PAINTER,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Christian ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Christian ",Mechanical Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Luis ",Assembly Technician,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Miguel ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Nathaniel ",Assembly Operations Lead,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Rodriguez, Ruben A.",Sr. Lead Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Rosales, Rogelio ",Lead Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Ruelas, Erika ",Senior Buyer,"Case, Nancy"
103098,Advanced Ground Systems Engineering LLC,"Ruiz, David ",Inventory Control,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Sambrano, Ferdinand V.",PAINTER,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Sandoval, Fabian ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Santa Maria, Ernest ",Fitter-Welder,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Scott, Michael ",Assembler,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Sierra, Brian ",DRIVER,"Ramos, Javier"
103098,Advanced Ground Systems Engineering LLC,"Sofian, Winarto ",Production Planning Engineer,"Nuguid, Mark Edmund Reyes"
103098,Advanced Ground Systems Engineering LLC,"Steele, Annette A.",Staff Accountant,"Tran, Tiffany"
103098,Advanced Ground Systems Engineering LLC,"Taylor-Pope, Aja L.",Senior Buyer,"Case, Nancy"
103098,Advanced Ground Systems Engineering LLC,"Trejo, Britney Z.",Production Coordinator,"Flores, Danny"
103098,Advanced Ground Systems Engineering LLC,"Valenzuela, Agustin ",Welder Helper,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Valenzuela, Alexis ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Vargas, Daniel ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Vargas, Ivan ",Mechanical Assembly Technician,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Vega, Oscar ",Assembler,"Villareal, Thomas A"
103098,Advanced Ground Systems Engineering LLC,"Villasenor, Luis M.",CNC Programmer,"Villegas, Saul"
103098,Advanced Ground Systems Engineering LLC,"Weissberg, Barbara ",Technical Illustrator/ Writer,"Cuevas, Gerald"
103098,Advanced Ground Systems Engineering LLC,"Zepeda, Bryan ",FITTER/WELDER,"Martinez, Martel"
103098,Advanced Ground Systems Engineering LLC,"Ziff, Kameron ",Product Development Engineer,"Garcia-Barron, Ohtli Aciz"
103098,Advanced Ground Systems Engineering LLC,"Zubia, Kelly ",Senior Painter,"Martinez, Martel"
103101,HYDRAULIC CRANES LLC,"Beltran-Ocampo, Joaquin ",Maintenance,"Petty, Pete"
103101,HYDRAULIC CRANES LLC,"Silva, Jason J.",Crane Salesman,"Petty, Pete"
103099,Otto Systems LP,"Frayre, Jorge ",Shipping & Receiving,"Otto, Paul"
103099,Otto Systems LP,"Lopez, Mauricio ",Assembler,"Otto, Paul"
103100,Westmont Industries Inc,"Cortez, Jorge ",MATERIAL DETAILER,"Hamilton, Lawrence"
103100,Westmont Industries Inc,"Cosey, Brandon ",FITTER/WELDER,"Hamilton, Lawrence"
103100,Westmont Industries Inc,"Fisher, Ryan ",FITTER/WELDER,"Hamilton, Lawrence"
103100,Westmont Industries Inc,"Fitch, Randolph ",Electrician,"Gutierrez, Jose Antonio"
103100,Westmont Industries Inc,"Llamas Ortega, Octavio ",Healthy & Safety Coordinator,"Gutierrez, Jose Antonio"
103100,Westmont Industries Inc,"Morey, Angela ",Principal Engineer,"Case, Stevan B"
103100,Westmont Industries Inc,"Nelson, Scott ",PROJECT ENGINEER,"Case, Stevan B"
103100,Westmont Industries Inc,"Raya, Jesus ",FITTER/WELDER,"Hamilton, Lawrence"
103100,Westmont Industries Inc,"Watson, Thomas ",PAINTER,"Hamilton, Lawrence"
103100,Westmont Industries Inc,"White, Matthew ",FITTER/WELDER,"Hamilton, Lawrence"`;
